// gen_idioms.js - 生成100个常用成语
const fs = require('fs');
const data = fs.readFileSync('miniapp/src/data.js', 'utf8');

const idioms = [
  {id:'i001',word:'画蛇添足',explanation:'比喻做了多余的事，反而有害无益。',source:'《战国策》',example:'他已经做得很好了，就不要再画蛇添足了。',tags:['寓言','教训']},
  {id:'i002',word:'守株待兔',explanation:'比喻不主动努力，而存万一的侥幸心理。',source:'《韩非子》',example:'学习不能守株待兔。',tags:['寓言','教训']},
  {id:'i003',word:'胸有成竹',explanation:'比喻做事之前已有通盘的考虑和谋划。',source:'苏轼',example:'他对这次比赛胸有成竹。',tags:['励志','准备']},
  {id:'i004',word:'卧薪尝胆',explanation:'形容人刻苦自励，发奋图强。',source:'《史记》',example:'我们要有卧薪尝胆的精神。',tags:['励志','历史']},
  {id:'i005',word:'亡羊补牢',explanation:'出了问题以后想办法补救，可以防止继续受损失。',source:'《战国策》',example:'亡羊补牢，为时不晚。',tags:['寓言','励志']},
  {id:'i006',word:'举一反三',explanation:'比喻从一件事情类推而知道其他许多事情。',source:'《论语》',example:'学习要能举一反三，才能融会贯通。',tags:['学习','哲理']},
  {id:'i007',word:'温故知新',explanation:'温习旧的知识，从而得到新的理解和体会。',source:'《论语》',example:'学习要做到温故知新。',tags:['学习','论语']},
  {id:'i008',word:'望梅止渴',explanation:'比喻用空想或假象来安慰自己。',source:'《世说新语》',example:'你这是望梅止渴，不解决实际问题。',tags:['寓言','哲理']},
  {id:'i009',word:'掩耳盗铃',explanation:'比喻自己欺骗自己，明明掩盖不住的事情偏要想法掩盖。',source:'《吕氏春秋》',example:'你这样做简直是掩耳盗铃。',tags:['寓言','教训']},
  {id:'i010',word:'鹏程万里',explanation:'比喻前程远大。',source:'《庄子》',example:'祝你鹏程万里，前途无量！',tags:['励志','祝福']},
  {id:'i011',word:'井底之蛙',explanation:'比喻见识狭窄的人。',source:'《庄子》',example:'我们不能做井底之蛙。',tags:['寓言','教训']},
  {id:'i012',word:'狐假虎威',explanation:'比喻依仗别人的势力欺压人。',source:'《战国策》',example:'他不过是狐假虎威罢了。',tags:['寓言','教训']},
  {id:'i013',word:'刻舟求剑',explanation:'比喻不懂事物已发展变化而仍静止地看问题。',source:'《吕氏春秋》',example:'这种做法无异于刻舟求剑。',tags:['寓言','哲理']},
  {id:'i014',word:'叶公好龙',explanation:'比喻口头上说爱好某事物，实际上并不真爱好。',source:'《新序》',example:'他不过是叶公好龙，并非真喜欢。',tags:['寓言','教训']},
  {id:'i015',word:'自相矛盾',explanation:'比喻自己说话做事前后抵触。',source:'《韩非子》',example:'你的话自相矛盾了。',tags:['寓言','逻辑']},
  {id:'i016',word:'杯弓蛇影',explanation:'比喻因疑神疑鬼而引起恐惧。',source:'《风俗通义》',example:'你别杯弓蛇影了，没那么可怕。',tags:['心理','疑惧']},
  {id:'i017',word:'画龙点睛',explanation:'比喻写文章或讲话时，在关键处用几句话点明实质。',source:'《历代名画记》',example:'这篇文章的结尾画龙点睛。',tags:['写作','艺术']},
  {id:'i018',word:'对牛弹琴',explanation:'比喻对不懂道理的人讲道理。',source:'《理惑论》',example:'跟他讲这些简直是对牛弹琴。',tags:['沟通','讽刺']},
  {id:'i019',word:'愚公移山',explanation:'比喻坚持不懈地改造自然和坚定不移地进行斗争。',source:'《列子》',example:'我们要有愚公移山的精神。',tags:['励志','坚持']},
  {id:'i020',word:'悬梁刺股',explanation:'形容刻苦学习。',source:'《战国策》',example:'古人悬梁刺股的精神值得学习。',tags:['学习','励志']},
  {id:'i021',word:'凿壁偷光',explanation:'形容家贫而读书刻苦。',source:'《西京杂记》',example:'我们要学习凿壁偷光的精神。',tags:['学习','励志']},
  {id:'i022',word:'闻鸡起舞',explanation:'比喻有志之士及时奋发。',source:'《晋书》',example:'年轻人应该闻鸡起舞，奋发向上。',tags:['励志','勤奋']},
  {id:'i023',word:'精卫填海',explanation:'比喻意志坚决，不畏艰难。',source:'《山海经》',example:'她有着精卫填海的毅力。',tags:['励志','坚持']},
  {id:'i024',word:'铁杵磨针',explanation:'比喻只要有决心，肯下工夫，多么难的事也能做成功。',source:'《方舆胜览》',example:'只要有铁杵磨针的精神，没有做不到的事。',tags:['励志','坚持']},
  {id:'i025',word:'程门立雪',explanation:'比喻尊敬师长，虔诚求学。',source:'《宋史》',example:'我们要学习程门立雪的精神。',tags:['学习','尊师']},
  {id:'i026',word:'三顾茅庐',explanation:'比喻真心诚意地邀请、拜访有才能的人。',source:'《三国志》',example:'为了请他出山，我三顾茅庐。',tags:['历史','诚意']},
  {id:'i027',word:'四面楚歌',explanation:'比喻陷入四面受敌、孤立无援的境地。',source:'《史记》',example:'公司现在四面楚歌，处境艰难。',tags:['历史','困境']},
  {id:'i028',word:'破釜沉舟',explanation:'比喻下决心不顾一切地干到底。',source:'《史记》',example:'我们要有破釜沉舟的决心。',tags:['励志','决心']},
  {id:'i029',word:'卧虎藏龙',explanation:'指隐藏着未被发现的人才。',source:'《北周书》',example:'这个小镇卧虎藏龙，高手如云。',tags:['人才','隐藏']},
  {id:'i030',word:'一字千金',explanation:'形容文辞精妙，不可更改。',source:'《史记》',example:'他的文章可谓一字千金。',tags:['写作','精华']},
  {id:'i031',word:'一鸣惊人',explanation:'比喻平时没有突出的表现，一下子做出惊人的成绩。',source:'《韩非子》',example:'他平时不声不响，这次一鸣惊人。',tags:['励志','成功']},
  {id:'i032',word:'一举两得',explanation:'做一件事得到两方面的好处。',source:'《晋书》',example:'这样安排可谓一举两得。',tags:['智慧','效率']},
  {id:'i033',word:'一箭双雕',explanation:'比喻做一件事达到两个目的。',source:'《北史》',example:'这个方案真是一箭双雕。',tags:['智慧','效率']},
  {id:'i034',word:'九牛一毛',explanation:'比喻极大数量中极微小的数量，微不足道。',source:'《史记》',example:'这点损失不过是九牛一毛。',tags:['数量','微小']},
  {id:'i035',word:'入木三分',explanation:'形容书法极有笔力。现多比喻分析问题很深刻。',source:'《书断》',example:'他的分析入木三分。',tags:['书法','深刻']},
  {id:'i036',word:'力挽狂澜',explanation:'比喻尽力挽回危险的局势。',source:'《进学解》',example:'在危急时刻，他力挽狂澜。',tags:['勇气','危机']},
  {id:'i037',word:'千钧一发',explanation:'形容情况十分危急。',source:'《汉书》',example:'在这千钧一发的时刻，他挺身而出。',tags:['紧急','危险']},
  {id:'i038',word:'口若悬河',explanation:'讲起话来滔滔不绝，像瀑布不停地奔流倾泻。',source:'《世说新语》',example:'他口若悬河，讲了两个小时。',tags:['口才','流利']},
  {id:'i039',word:'门庭若市',explanation:'形容来的人很多，非常热闹。',source:'《战国策》',example:'这家店开业后门庭若市。',tags:['热闹','人气']},
  {id:'i040',word:'开卷有益',explanation:'读书总有益处。形容读书有好处。',source:'《渑水燕谈录》',example:'开卷有益，要多读书。',tags:['学习','读书']},
  {id:'i041',word:'天衣无缝',explanation:'比喻事物周密完善，找不出什么毛病。',source:'《灵怪录》',example:'这个计划天衣无缝。',tags:['完美','周密']},
  {id:'i042',word:'才高八斗',explanation:'形容人的文才极高。',source:'《南史》',example:'他可谓才高八斗。',tags:['才华','文学']},
  {id:'i043',word:'不可思议',explanation:'原有神秘奥妙的意思。现多指无法想象，难以理解。',source:'《维摩诘所说经》',example:'这件事真是不可思议。',tags:['神奇','难以理解']},
  {id:'i044',word:'出类拔萃',explanation:'超出同类之上。多指人的品德才能。',source:'《孟子》',example:'他在同龄人中出类拔萃。',tags:['优秀','才华']},
  {id:'i045',word:'叶落归根',explanation:'比喻事物有一定的归宿。多指客居他乡的人，终要回到本乡。',source:'《景德传灯录》',example:'老人想叶落归根，回到故乡。',tags:['故乡','归宿']},
  {id:'i046',word:'宁死不屈',explanation:'宁愿死也不屈服。',source:'《宋书》',example:'他宁死不屈的精神令人敬佩。',tags:['气节','坚强']},
  {id:'i047',word:'对答如流',explanation:'回答问话像流水一样快。形容口才好，反应快。',source:'《北齐书》',example:'面对老师的提问，他对答如流。',tags:['口才','聪明']},
  {id:'i048',word:'后来居上',explanation:'后来的超过先前的。',source:'《史记》',example:'年轻人后来居上，值得高兴。',tags:['进步','超越']},
  {id:'i049',word:'名列前茅',explanation:'比喻名次列在前面。',source:'《左传》',example:'他每次考试都名列前茅。',tags:['优秀','成绩']},
  {id:'i050',word:'名落孙山',explanation:'比喻考试或选拔没有录取。',source:'《过庭录》',example:'这次考试他名落孙山。',tags:['失败','考试']},
  {id:'i051',word:'如鱼得水',explanation:'比喻得到和自己十分投合的人或对自己很合适的环境。',source:'《三国志》',example:'来到这个新环境，他如鱼得水。',tags:['适应','合适']},
  {id:'i052',word:'如虎添翼',explanation:'比喻强大的又得到了援助。',source:'《三国演义》',example:'有了这个新设备，真是如虎添翼。',tags:['强大','助力']},
  {id:'i053',word:'如雷贯耳',explanation:'像雷声传入耳朵那样响亮。比喻人的名声很大。',source:'《三国演义》',example:'久闻大名，如雷贯耳。',tags:['名声','敬仰']},
  {id:'i054',word:'安居乐业',explanation:'指安定愉快地生活和劳动。',source:'《老子》',example:'人民安居乐业，社会和谐稳定。',tags:['生活','和谐']},
  {id:'i055',word:'宠辱不惊',explanation:'受宠受辱都不在乎。指不因个人得失而动心。',source:'《新唐书》',example:'他宠辱不惊，始终保持平和心态。',tags:['心态','淡泊']},
  {id:'i056',word:'志同道合',explanation:'志趣相同，意见一致。',source:'《三国志》',example:'我们志同道合，一起创业。',tags:['友谊','合作']},
  {id:'i057',word:'呕心沥血',explanation:'比喻用尽心思。多形容为事业、工作、文艺创作等用心的艰苦。',source:'《新唐书》',example:'为了这个项目，他呕心沥血。',tags:['用心','艰苦']},
  {id:'i058',word:'从容不迫',explanation:'不慌不忙，沉着镇定。',source:'《庄子》',example:'面对危险，他从容不迫。',tags:['沉着','冷静']},
  {id:'i059',word:'事半功倍',explanation:'指做事得法，因而费力小，收效大。',source:'《孟子》',example:'用对方法，可以事半功倍。',tags:['效率','方法']},
  {id:'i060',word:'功亏一篑',explanation:'比喻做事情只差最后一点没能完成。',source:'《尚书》',example:'就差最后一步了，不能功亏一篑。',tags:['失败','坚持']},
  {id:'i061',word:'厉兵秣马',explanation:'磨好兵器，喂好马。形容准备战斗。',source:'《左传》',example:'我们已经厉兵秣马，准备迎接挑战。',tags:['准备','战斗']},
  {id:'i062',word:'叹为观止',explanation:'指赞美所见到的事物好到了极点。',source:'《左传》',example:'这场表演令人叹为观止。',tags:['赞美','极致']},
  {id:'i063',word:'唯利是图',explanation:'只要有利可图，什么事都干。',source:'《抱朴子》',example:'他这个人唯利是图，不可深交。',tags:['利益','贬义']},
  {id:'i064',word:'围魏救赵',explanation:'指攻击敌人后方的据点以迫使进攻之敌撤退的战术。',source:'《史记》',example:'我们可以采用围魏救赵的策略。',tags:['军事','策略']},
  {id:'i065',word:'孜孜不倦',explanation:'指工作或学习勤奋不知疲倦。',source:'《尚书》',example:'他孜孜不倦地学习。',tags:['勤奋','学习']},
  {id:'i066',word:'岿然不动',explanation:'像高山一样挺立着一动不动。比喻立场坚定，不可动摇。',source:'《淮南子》',example:'面对诱惑，他岿然不动。',tags:['坚定','立场']},
  {id:'i067',word:'原形毕露',explanation:'本来面目完全暴露。',source:'《大学》',example:'在证据面前，他的原形毕露。',tags:['暴露','真相']},
  {id:'i068',word:'唇亡齿寒',explanation:'比喻利害密切相关。',source:'《左传》',example:'我们两国唇亡齿寒，要互相帮助。',tags:['关系','密切']},
  {id:'i069',word:'宾至如归',explanation:'客人到这里就像回到自己家里一样。形容招待客人热情周到。',source:'《左传》',example:'这家酒店服务周到，让人宾至如归。',tags:['热情','招待']},
  {id:'i070',word:'家喻户晓',explanation:'家家户户都知道。形容人所共知。',source:'《论语集注》',example:'这个故事家喻户晓。',tags:['知名','普及']},
  {id:'i071',word:'得天独厚',explanation:'具备的条件特别优越，所处环境特别好。',source:'《陈书》',example:'这里得天独厚，适合发展旅游。',tags:['优越','环境']},
  {id:'i072',word:'患得患失',explanation:'担心得不到，得到了又担心失掉。形容对个人得失看得很重。',source:'《论语》',example:'做人不能患得患失。',tags:['心态','得失']},
  {id:'i073',word:'惴惴不安',explanation:'形容因害怕或担心而不安。',source:'《诗经》',example:'他惴惴不安地等待结果。',tags:['担心','不安']},
  {id:'i074',word:'抱薪救火',explanation:'比喻用错误的方法去消除灾祸，结果使灾祸反而扩大。',source:'《史记》',example:'这种做法无异于抱薪救火。',tags:['错误','方法']},
  {id:'i075',word:'拨乱反正',explanation:'消除混乱局面，恢复正常秩序。',source:'《公羊传》',example:'我们要拨乱反正，回归正轨。',tags:['纠正','秩序']},
  {id:'i076',word:'歧路亡羊',explanation:'比喻事物复杂多变，没有正确的方向就会误入歧途。',source:'《列子》',example:'面对众多选择，要小心歧路亡羊。',tags:['选择','方向']},
  {id:'i077',word:'杯水车薪',explanation:'比喻力量太小，解决不了问题。',source:'《孟子》',example:'这点帮助不过是杯水车薪。',tags:['无力','微小']},
  {id:'i078',word:'齐心协力',explanation:'思想认识一致，共同努力。',source:'《墨子》',example:'大家齐心协力，一定能成功。',tags:['合作','团结']},
  {id:'i079',word:'精益求精',explanation:'好了还求更好。',source:'《论语》',example:'他对工作精益求精。',tags:['追求','完美']},
  {id:'i080',word:'绰绰有余',explanation:'形容房屋或钱财非常宽裕，用不完。',source:'《诗经》',example:'这点任务对他来说绰绰有余。',tags:['充足','富裕']},
  {id:'i081',word:'耳濡目染',explanation:'耳朵经常听到，眼睛经常看到，不知不觉地受到影响。',source:'《颜氏家训》',example:'在孩子教育上，耳濡目染很重要。',tags:['影响','环境']},
  {id:'i082',word:'自食其果',explanation:'指自己做了坏事，自己受到损害或惩罚。',source:'《新唐书》',example:'他最终自食其果。',tags:['后果','报应']},
  {id:'i083',word:'舍生取义',explanation:'舍弃生命以保全正义。',source:'《孟子》',example:'革命先烈舍生取义的精神值得我们学习。',tags:['正义','牺牲']},
  {id:'i084',word:'花好月圆',explanation:'比喻美好圆满。',source:'《物妖志》',example:'祝你花好月圆，幸福美满。',tags:['祝福','美好']},
  {id:'i085',word:'见异思迁',explanation:'看见另一个事物就想改变原来的主意。指意志不坚定，喜爱不专一。',source:'《管子》',example:'做人不能见异思迁。',tags:['不专','意志']},
  {id:'i086',word:'见贤思齐',explanation:'见到德才兼备的人就想赶上他。',source:'《论语》',example:'我们要见贤思齐，向优秀的人学习。',tags:['学习','进步']},
  {id:'i087',word:'归根结底',explanation:'归结到根本上。',source:'《朱子语类》',example:'归根结底，还是态度问题。',tags:['根本','总结']},
  {id:'i088',word:'纵虎归山',explanation:'把老虎放回山去。比喻把坏人放回老巢，留下祸根。',source:'《三国志》',example:'不能纵虎归山，要彻底解决问题。',tags:['祸根','危险']},
  {id:'i089',word:'纸上谈兵',explanation:'在纸面上谈论打仗。比喻空谈理论，不能解决实际问题。',source:'《史记》',example:'我们不能纸上谈兵，要付诸实践。',tags:['空谈','实践']},
  {id:'i090',word:'纲举目张',explanation:'比喻抓住主要的环节，就能带动一切。',source:'《吕氏春秋》',example:'做事要纲举目张，抓住重点。',tags:['方法','重点']},
  {id:'i091',word:'绰约多姿',explanation:'形容女子姿态柔美。',source:'《庄子》',example:'她舞姿绰约多姿。',tags:['美丽','姿态']},
  {id:'i092',word:'翻然改进',explanation:'形容很快转变，有所进步。',source:'《新唐书》',example:'希望你翻然改进，重新做人。',tags:['改进','进步']},
  {id:'i093',word:'翻然悔悟',explanation:'形容很快地醒悟过来。',source:'《宋史》',example:'在事实面前，他翻然悔悟。',tags:['悔悟','醒悟']},
  {id:'i094',word:'乘风破浪',explanation:'比喻志向远大，不畏艰险，奋勇前进。',source:'《宋书》',example:'让我们乘风破浪，勇往直前！',tags:['励志','勇敢']},
  {id:'i095',word:'饮水思源',explanation:'喝水的时候想起水是从哪儿来的。比喻不忘本。',source:'《征调曲》',example:'我们要饮水思源，不忘恩人。',tags:['感恩','不忘本']},
  {id:'i096',word:'记忆犹新',explanation:'过去的事，至今印象还非常清楚。',source:'《南史》',example:'那件事我记忆犹新。',tags:['记忆','清晰']},
  {id:'i097',word:'孜孜以求',explanation:'不知疲倦地探求。',source:'《尚书》',example:'他孜孜以求，终于取得了成功。',tags:['追求','勤奋']},
  {id:'i098',word:'梦寐以求',explanation:'做梦的时候都在追求。形容迫切地期望着。',source:'《诗经》',example:'这正是我梦寐以求的机会。',tags:['期望','渴望']},
  {id:'i099',word:'志存高远',explanation:'追求远大的理想及对事业上的抱负。',source:'《三国志》',example:'年轻人要志存高远。',tags:['志向','抱负']},
  {id:'i100',word:'脚踏实地',explanation:'比喻做事踏实，认真。',source:'《邵氏闻见录》',example:'做人要脚踏实地，不要好高骛远。',tags:['踏实','认真']}
];

// 替换 data.js 中的 idioms 数组
const idiomsStart = data.indexOf('const idioms = [');
const idiomsEnd = data.indexOf('];', idiomsStart) + 2;
const newIdioms = 'const idioms = ' + JSON.stringify(idioms, null, 2) + ';';
const newData = data.substring(0, idiomsStart) + newIdioms + data.substring(idiomsEnd);

fs.writeFileSync('miniapp/src/data.js', newData, 'utf8');
console.log('成语数据已更新！共', idioms.length, '个成语');
